{
  "hash": "6452697a0bc7698d17b332d4a44d8ebf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Your Title\"\nabstract: |\n  **Background**: (Brief few sentences)\n  **Objectives**: \n    1. Estimate the causal effect of YOUR EXPOSURE on YOUR OUTCOMES measured one year later.\n    2. Evaluate whether these effects vary across the population.\n    3. Provide policy guidance on which individuals might benefit most.\n  **Method**: We conducted a three-wave retrospective cohort study (waves XX-XXX, October XXXX--October XXXX) using data *SIMULATED* from the New Zealand Attitudes and Values Study, a nationally representative panel. Participants were eligible if they participated in the NZAVS in the baseline wave (XXXX,...). We defined the exposure as (XXXX  > NUMBER on a 1-7 Likert Scale (1 = yes, 0 = no)). To address attrition, we applied inverse probability of censoring weights; to improve external validity, we applied weights to the population distribution of Age, Ethnicity, and Gender. We computed expected mean outcomes for the population in each exposure condition (high XXXX/low XXXXX). Under standard causal assumptions of unconfoundedness, the contrast provides an unbiased average treatment effect. We then used causal forests to detect heterogeneity in these effects and employed policy tree algorithms to identify individuals (\"strong responders\") likely to experience the greatest benefits.\n  **Results**:   Increasing XXXXX leads to XXXXX. Heterogeneous responses to (e.g. *Forgiveness*, *Personal Well-Being*, and *Life-Satisfaction*...) reveal structural variability in subpopulations...\n  **Implications**: (Brief few sentences)\n  **Keywords**: *Causal Inference*;  *Cross-validation*; *Distress*; *Employment*; *Longitudinal*; *Machine Learning*; *Religion*; *Semi-parametric*; *Targeted Learning*.\nauthor: \n  - name: YOUR NAME\n    affiliation: Victoria University of Wellington, New Zealand\n    email: XXXXX\n    corresponding: yes\nkeywords: [Causal Inference, Cross-validation,...]\neditor_options: \n  chunk_output_type: console\ndate: \"last-modified\"\nfontfamily: libertinus\nbibliography: references.bib\ncsl: apa7.csl\nformat:\n  docx: # comment this out if you want pdf\n    default: false  # comment this out if you want pdf\n  pdf:\n    pdf-engine: lualatex\n    sanitise: true\n    keep-tex: true\n    link-citations: true\n    colorlinks: true\n    documentclass: article\n    classoption: [\"single column\"]\n    lof: false\n    lot: false\n    geometry:\n      - top=30mm\n      - left=25mm\n      - heightrounded\n      - headsep=22pt\n      - headheight=11pt\n      - footskip=33pt\n      - ignorehead\n      - ignorefoot\n    header-includes:\n      - \\let\\oldtabular\\tabular\n      - \\renewcommand{\\tabular}{\\small\\oldtabular}\n      - \\setlength{\\tabcolsep}{4pt}  # adjust this value as needed\nexecute:\n  echo: false\n  warning: false\n  include: true\n  eval: true\n---\n\n\n\n{{< pagebreak >}}\n\n## Introduction\n\n**Your place to shine here**\n\n## Method\n\n\n\n{{< pagebreak >}}\n\n## Results\n\n### Average Treatment Effects\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Average Treatment Effects on Multi-dimensional Wellbeing](new_initial_quarto_document_files/figure-html/fig-ate-1.png){#fig-ate width=768}\n:::\n:::\n\n\n{{< pagebreak >}}\n\n\n::: {#tbl-outcomes .cell tbl-cap='Average Treatment Effects on Multi-dimensional Wellbeing'}\n::: {.cell-output-display}\n\n\n|Outcome                     |ATE       |2.5 %     |97.5 %    |E-Value   |E-Value bound |\n|:---------------------------|:---------|:---------|:---------|:---------|:-------------|\n|**Social Belonging**        |**0.133** |**0.09**  |**0.177** |**1.51**  |**1.39**      |\n|**Neighbourhood Community** |**0.114** |**0.07**  |**0.159** |**1.458** |**1.328**     |\n|**Self Esteem**             |**0.099** |**0.06**  |**0.139** |**1.415** |**1.299**     |\n|**Social Support**          |**0.098** |**0.055** |**0.141** |**1.413** |**1.284**     |\n|**Meaning: Purpose**        |**0.104** |**0.053** |**0.154** |**1.43**  |**1.278**     |\n|**Meaning: Sense**          |**0.094** |**0.043** |**0.145** |**1.401** |**1.244**     |\n|Depression                  |-0.065    |-0.112    |-0.017    |1.315     |1.146         |\n|Anxiety                     |-0.06     |-0.104    |-0.016    |1.3       |1.141         |\n|Life Satisfaction           |0.056     |0.012     |0.1       |1.287     |1.121         |\n|Personal Well-being Index   |0.055     |0.013     |0.098     |1.284     |1.116         |\n|Rumination                  |-0.051    |-0.102    |-0.001    |1.271     |1.012         |\n|Hours of Exercise (log)     |-0.02     |-0.074    |0.034     |1.155     |1             |\n\n\n:::\n:::\n\n\nConfidence intervals were adjusted for multiple comparisons using bonferroni correction ($\\alpha$ = 0.05). E‑values were also adjusted using bonferroni correction ($\\alpha$ = 0.05).\n\nThe following outcomes showed reliable causal evidence (E‑value lower bound > 1.2):\n\n- Social Belonging: 0.133(0.069,0.197); on the original scale, 0.145 (0.075,0.215).  E‑value bound = 1.329\n- Neighbourhood Community: 0.114(0.049,0.179); on the original scale, 0.179 (0.077,0.281).  E‑value bound = 1.264\n- Self Esteem: 0.099(0.041,0.157); on the original scale, 0.126 (0.052,0.2).  E‑value bound = 1.238\n- Social Support: 0.098(0.035,0.161); on the original scale, 0.11 (0.039,0.18).  E‑value bound = 1.216\n\n{{< pagebreak >}}\n\n<!-- OPTIONAL SECTION: PLANNED SUBGROUP COMPARISONS -->\n<!-- uncomment the section below if you performed subgroup analysis -->\n\n<!-- ### Planned Subgroup Comparisons -->\n\n<!-- Based on theoretical findings we expected that the effects of {name_exposure} would vary by age...\\@fig-planned-comparison and @tbl-planned-comparison -->\n\n<!-- ```{r} -->\n<!-- #| label: fig-planned-comparison -->\n<!-- #| fig-cap: \"Planned Comparison Plot\" -->\n<!-- #| eval: true -->\n<!-- #| echo: false -->\n<!-- #| fig-height: 10 -->\n<!-- #| fig-width: 12 -->\n<!-- plots_subgroup_age_young_old -->\n<!-- ``` -->\n\n<!-- ```{r} -->\n<!-- #| label: tbl-planned-comparison -->\n<!-- #| tbl-cap: \"Planned Comparison Table\" -->\n<!-- #| eval: true -->\n<!-- #| echo: false -->\n<!-- group_comparison_age_young_old$results |>  -->\n<!--   mutate(across(where(is.numeric), ~ round(., 2))) %>% -->\n<!--   kbl(format = \"markdown\") -->\n<!-- ``` -->\n\n<!-- ```{r, results = 'asis'} -->\n<!-- #| eval: false # copy and paste your own text -->\n<!-- cat(group_comparison_age_young_old$interpretation) -->\n<!-- ``` -->\n\n{{< pagebreak >}}\n\n### Heterogeneous Treatment Effects {#results-qini-curve}\n\nWe begin by examining the distribution of individual treatment effects (τᵢ) across our sample. @fig-tau-distribution presents the estimated treatment effects for each individual, revealing substantial variability in how people respond to {name_exposure_lower}.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of Individual Treatment Effects (τᵢ) Across Outcomes](new_initial_quarto_document_files/figure-html/fig-tau-distribution-1.png){#fig-tau-distribution width=960}\n:::\n:::\n\n\nThe histograms above show considerable heterogeneity in treatment effects across individuals. To determine whether this variability is systematic (i.e., predictable based on individual characteristics) rather than random noise, we employ two complementary approaches: Qini curves to assess the reliability of heterogeneous effects, and policy trees to identify subgroups with differential treatment responses.\n\n\n\n\n\n<!-- only include this table if you have multiple qini results -->\n\n::: {.cell tbl-cap='Qini Curve Results'}\n::: {.cell-output-display}\n\n\nTable: Qini Curve Results\n\n|Model                     |Spend 20%             |Spend 50%              |\n|:-------------------------|:---------------------|:----------------------|\n|Social Belonging          |0.03 [-0.00, 0.07]    |0.00 [-0.05, 0.05]     |\n|Anxiety (reversed)        |-0.00 [-0.01, 0.01]   |-0.00 [-0.01, 0.01]    |\n|Depression (reversed)     |-0.00 [-0.01, 0.01]   |-0.00 [-0.01, 0.01]    |\n|Life Satisfaction         |**0.09 [0.05, 0.13]** |**0.09 [0.03, 0.14]**  |\n|Hours of Exercise (log)   |0.01 [-0.02, 0.04]    |-0.02 [-0.07, 0.03]    |\n|Meaning: Purpose          |**0.08 [0.05, 0.12]** |**0.08 [0.03, 0.13]**  |\n|Meaning: Sense            |**0.08 [0.04, 0.12]** |**0.07 [0.02, 0.12]**  |\n|Neighbourhood Community   |**0.09 [0.05, 0.12]** |0.03 [-0.02, 0.08]     |\n|Personal Well-being Index |**0.10 [0.06, 0.13]** |**0.09 [0.03, 0.14]**  |\n|Rumination (reversed)     |-0.01 [-0.03, 0.01]   |*-0.04 [-0.06, -0.01]* |\n|Self Esteem               |**0.06 [0.03, 0.10]** |**0.07 [0.02, 0.11]**  |\n|Social Support            |**0.10 [0.06, 0.13]** |**0.07 [0.02, 0.13]**  |\n\n\n:::\n:::\n\n\n<!-- only include figures if you have qini results -->\n\n::: {.cell}\n::: {.cell-output-display}\n![Qini Curves for Heterogeneous Treatment Effects](new_initial_quarto_document_files/figure-html/fig-qini-combined-1.png){#fig-qini-combined width=1152}\n:::\n:::\n\n\n{{< pagebreak >}}\n\n### Decision Rules (Who is Most Sensitive to Treatment?)\n\n\n\nThe following pages present policy trees for each outcome with reliable heterogeneous effects. Each tree shows: (1) the decision rules for treatment assignment, (2) the distribution of treatment effects across subgroups, and (3) visual representation of how covariates split the population into groups with differential treatment responses.\n\n<!-- the following policy tree figures are optional -->\n<!-- only include as many as you have valid policy trees -->\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n#### Policy Tree 1: Life Satisfaction\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\n\n{{< pagebreak >}}\n\n\n\n#### Policy Tree 2: Meaning: Purpose\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\n\n{{< pagebreak >}}\n\n\n\n#### Policy Tree 3: Meaning: Sense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\n\n{{< pagebreak >}}\n\n\n\n#### Policy Tree 4: Neighbourhood Community\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\n\n{{< pagebreak >}}\n\n\n\n#### Policy Tree 5: Personal Well-being Index\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\n\n{{< pagebreak >}}\n\n\n\n#### Policy Tree 6: Self Esteem\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\n\n{{< pagebreak >}}\n\n\n\n#### Policy Tree 7: Social Support\n```\n\n\n:::\n\n\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-1.png){#fig-policy-trees-1 width=1152}\n:::\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-2.png){#fig-policy-trees-2 width=1152}\n:::\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-3.png){#fig-policy-trees-3 width=1152}\n:::\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-4.png){#fig-policy-trees-4 width=1152}\n:::\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-5.png){#fig-policy-trees-5 width=1152}\n:::\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-6.png){#fig-policy-trees-6 width=1152}\n:::\n\n::: {.cell-output-display}\n![Policy Trees for Treatment Assignment](new_initial_quarto_document_files/figure-html/fig-policy-trees-7.png){#fig-policy-trees-7 width=1152}\n:::\n:::\n\n\n\n\n{{< pagebreak >}}\n\n## Discussion\n\n\n\n{{< pagebreak >}}\n\n## Appendix A: Measures {#appendix-measures}\n\n### Measures\n\n#### Baseline Covariate Measures\n\n### Baseline Covariates\n\n#### Age\n\n*What is your date of birth?*\n\nWe asked participants' ages in an open-ended question (\"What is your age?\" or \"What is your date of birth\"). [@sibley2021]\n\n#### Agreeableness\n\n*I sympathize with others' feelings.*\n*I am not interested in other people's problems.*\n*I feel others' emotions.*\n*I am not really interested in others (reversed).*\n\nMini-IPIP6 Agreeableness dimension: (i) I sympathize with others' feelings. (ii) I am not interested in other people's problems. (r) (iii) I feel others' emotions. (iv) I am not really interested in others. (r) [@sibley2011]\n\n#### Alcohol Frequency\n\n*\"How often do you have a drink containing alcohol?\"*\n\nParticipants could chose between the following responses: '(1 = Never - I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to 3 times a week, 5 = 4 or more times a week, 6 = Don't know)' [@Ministry_of_Health_2013]\n\n#### Alcohol Intensity\n\n*\"How many drinks containing alcohol do you have on a typical day when drinking alcohol? (number of drinks on a typical day when drinking)\"*\n\nParticipants responded using an open-ended box. [@Ministry_of_Health_2013]\n\n#### Social Belonging\n\n*Know that people in my life accept and value me.*\n*Feel like an outsider (reversed).*\n*Know that people around me share my attitudes and beliefs.*\n\nWe assessed felt belongingness with three items adapted from the Sense of Belonging Instrument (Hagerty & Patusky, 1995): (1) \"Know that people in my life accept and value me\"; (2) \"Feel like an outsider\"; (3) \"Know that people around me share my attitudes and beliefs\". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded. [@hagerty1995]\n\n#### Born in Nz\n\n*Where were you born? (please be specific, e.g., which town/city?)*\n\nCoded binary (1 = New Zealand; 0 = elsewhere.)\n [@sibley2021]\n\n#### Conscientiousness\n\n*I get chores done right away.*\n*I like order.*\n*I make a mess of things.*\n*I often forget to put things back in their proper place.*\n\nMini-IPIP6 Conscientiousness dimension: (i) I get chores done right away. (ii) I like order. (iii) I make a mess of things. (r) (iv) I often forget to put things back in their proper place. (r) [@sibley2011]\n\n#### Education Level\n\n*What is your highest level of qualification?*\n\nWe asked participants, \"What is your highest level of qualification?\". We coded participans highest finished degree according to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with overseas school qualifications coded as Level 3, and all other ancillary categories coded as missing) [@sibley2021]\n\n#### Employed\n\n*Are you currently employed (This includes self-employed of casual work)?*\n\nBinary response: (0 = No, 1 = Yes) [@statsnz_ssga18]\n\n#### Ethnicity\n\n*Which ethnic group(s) do you belong to?*\n\nCoded string: (1 = New Zealand European; 2 = Māori; 3 = Pacific; 4 = Asian) [@statsnz_ssga18]\n\n#### Disability Status\n\n*Do you have a health condition or disability that limits you and that has lasted for 6+ months?*\n\nWe assessed disability with a one-item indicator adapted from Verbrugge (1997). It asks, \"Do you have a health condition or disability that limits you and that has lasted for 6+ months?\" (1 = Yes, 0 = No). [@verbrugge1997]\n\n#### Log Hours with Children\n\n*Hours spent...looking after children.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Log Hours Commuting\n\n*Hours spent...travelling/commuting.*\n\nWe took the natural log of the response + 1. [@sibley2021]\n\n#### Log Hours of Exercise\n\n*Hours spent...exercising/physical activity.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Log Hours on Housework\n\n*Hours spent...housework/cooking.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Log Household Income\n\n*Please estimate your total household income (before tax) for the year XXXX.*\n\nWe took the natural log of the response + 1. [@sibley2021]\n\n#### Male\n\n*We asked participants’ gender in an open-ended question: \"what is your gender?\"*\n\nHere, we coded all those who responded as Male as 1, and those who did not as 0.\n [@fraser_coding_2020]\n\n#### Neuroticism\n\n*I have frequent mood swings.*\n*I am relaxed most of the time (reversed).*\n*I get upset easily.*\n*I seldom feel blue (reversed).*\n\nMini-IPIP6 Neuroticism dimension: (i) I have frequent mood swings. (ii) I am relaxed most of the time. (r) (iii) I get upset easily. (iv) I seldom feel blue. (r) [@sibley2011]\n\n#### Non Heterosexual\n\n*How would you describe your sexual orientation? (e.g., heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)*\n\nOpen-ended question, coded as binary (not heterosexual = 1). [@greaves2017diversity]\n\n#### Nz Deprivation Index\n\n*New Zealand Deprivation - Decile Index - Using 2018 Census Data*\n\nNumerical: (1-10) [@atkinson2019]\n\n#### Occupational Prestige Index\n\n*We assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13).*\n\nThis index uses the income, age, and education of a reference group, in this case, the 2013 New Zealand census, to calculate a score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant a NZSEI-13 score based on their occupation.\n [@fahy2017]\n\n#### Openness\n\n*I have a vivid imagination.*\n*I have difficulty understanding abstract ideas (reversed).*\n*I do not have a good imagination (reversed).*\n*I am not interested in abstract ideas (reversed).*\n\nMini-IPIP6 Openness to Experience dimension: (i) I have a vivid imagination. (ii) I have difficulty understanding abstract ideas. (r) (iii) I do not have a good imagination. (r) (iv) I am not interested in abstract ideas. (r) [@sibley2011]\n\n#### Parent\n\n*If you are a parent, in which year was your eldest child born?*\n\nParents were coded as 1, while the others were coded as 0.\n [@sibley2021]\n\n#### Has Partner\n\n*What is your relationship status? (e.g., single, married, de-facto, civil union, widowed, living together, etc.)*\n\nCoded as binary (has partner = 1). [@sibley2021]\n\n#### Political Conservatism\n\n*Please rate how politically liberal versus conservative you see yourself as being.*\n\nOrdinal response: (1 = Extremely Liberal, 7 = Extremely Conservative)\n [@jost_end_2006-1]\n\n#### Major Religions\n\n*Do you identify with a religion and/or spiritual group? --> (If yes...)--> What religion or spiritual group?*\n\nOpen-ended (string). Coded from New Zealand Census Categories. Levels are: \"Not Religious\",\"Anglican\",\"Buddhist\", \"Catholic\", \"Christian (Non-Denominational)\", \"Christian (Other Denominations)\",\"Hindu\", \"Jewish\", \"Muslim\",\"Presbyterian, Congregational, Reformed\", \"Other Religions\".\n [@sibley2021]\n\n#### Religious Identification\n\n*How important is your religion to how you see yourself?*\n\nOrdinal response: (1 = Not Important, 7 = Very Important) [@sibley2021]\n\n#### Rural Classification\n\n*High Urban Accessibility = 1, Medium Urban Accessibility = 2, Low Urban Accessibility  = 3, Remote = 4, Very Remote = 5.*\n\n\"Participants residence locations were coded according to a five-level ordinal categorisation ranging from Urban to Rural.\" [@whitehead2023unmasking]\n\n#### Sample Frame Opt in\n\n*Participant was not randomly sampled from the New Zealand Electoral Roll.*\n\nCode string (Binary): (0 = No, 1 = Yes) [@sibley2021]\n\n#### Short Form Health\n\n*In general, would you say your health is...*\n\nOrdinal response: (1 = Poor, 7 = Excellent) [@instrument1992mos]\n\n#### Smoker\n\n*Do you currently smoke tobacco cigarettes?*\n\nBinary smoking indicator (0 = No, 1 = Yes). [@sibley2021]\n\n#### Exposure Measures\n\n### Exposure Variable\n\n#### Extraversion\n\n*I am the life of the party.*\n*I don't talk a lot (reversed).*\n*I keep in the background (reversed).*\n*I talk to a lot of different people at parties.*\n\nMini-IPIP6 Extraversion dimension: (i) I am the life of the party. (ii) I don't talk a lot. (r) (iii) I keep in the background. (r) (iv) I talk to a lot of different people at parties. [@sibley2011]\n\n#### Outcome Measures\n\n### Outcome Variables\n\n#### Social Belonging\n\n*Know that people in my life accept and value me.*\n*Feel like an outsider (reversed).*\n*Know that people around me share my attitudes and beliefs.*\n\nWe assessed felt belongingness with three items adapted from the Sense of Belonging Instrument (Hagerty & Patusky, 1995): (1) \"Know that people in my life accept and value me\"; (2) \"Feel like an outsider\"; (3) \"Know that people around me share my attitudes and beliefs\". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded. [@hagerty1995]\n\n#### Anxiety\n\n*During the past 30 days, how often did...you feel restless or fidgety?*\n*During the past 30 days, how often did...you feel that everything was an effort?*\n*During the past 30 days, how often did...you feel nervous?*\n\nOrdinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2= Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time) [@kessler2002]\n\n#### Depression\n\n*During the past 30 days, how often did...you feel hopeless?*\n*During the past 30 days, how often did...you feel so depressed that nothing could cheer you up?*\n*During the past 30 days, how often did...you feel you feel restless or fidgety?*\n\nOrdinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2= Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time) [@kessler2002]\n\n#### Life Satisfaction\n\n*I am satisfied with my life.*\n*In most ways my life is close to ideal.*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@diener1985a]\n\n#### Log Hours of Exercise\n\n*Hours spent...exercising/physical activity.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Meaning Purpose\n\n*My life has a clear sense of purpose*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@steger_meaning_2006]\n\n#### Meaning Sense\n\n*I have a good sense of what makes my life meaningful.*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@steger_meaning_2006]\n\n#### Neighbourhood Community\n\n*I feel a sense of community with others in my local neighbourhood.*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@sengupta2013]\n\n#### Personal Well Being Index\n\nno information available for this variable.\n\n#### Rumination\n\n*During the last 30 days, how often did...you have negative thoughts that repeated over and over?*\n\nOrdinal responses: 0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time. [@nolen-hoeksema_effects_1993]\n\n#### Self Esteem\n\n*On the whole am satisfied with myself.*\n*Take a positive attitude toward myself.*\n*Am inclined to feel that I am a failure (reversed).*\n\nOrdinal response (1 = Very inaccurate to 7 = Very accurate). [@Rosenberg1965]\n\n#### Social Support\n\n*There are people I can depend on to help me if I really need it.*\n*There is no one I can turn to for guidance in times of stress (reversed).*\n*I know there are people I can turn to when I need help.*\n\nOrdinal response: (1 = Strongly Disagree, 7 = Strongly Agree) [@cutrona1987]\n\n{{< pagebreak >}}\n\n## Appendix B: Sample Characteristics {#appendix-sample}\n\n#### Sample Statistics: Baseline Covariates\n\n@tbl-appendix-baseline presents sample demographic statistics.\n\n::: {#tbl-appendix-baseline}\n\n|                                |2018               |\n|:-------------------------------|:------------------|\n|                                |(N=39635)          |\n|**Age**                         |                   |\n|Mean (SD)                       |48.5 (13.9)        |\n|Median [Min, Max]               |51.0 [18.0, 99.0]  |\n|**Agreeableness**               |                   |\n|Mean (SD)                       |5.35 (0.988)       |\n|Median [Min, Max]               |5.47 [1.00, 7.00]  |\n|Missing                         |9 (0.0%)           |\n|**Alcohol Frequency**           |                   |\n|Mean (SD)                       |2.16 (1.34)        |\n|Median [Min, Max]               |2.00 [0, 5.00]     |\n|Missing                         |1342 (3.4%)        |\n|**Alcohol Intensity**           |                   |\n|Mean (SD)                       |2.15 (2.09)        |\n|Median [Min, Max]               |2.00 [0, 15.0]     |\n|Missing                         |2348 (5.9%)        |\n|**Belong**                      |                   |\n|Mean (SD)                       |5.14 (1.07)        |\n|Median [Min, Max]               |5.31 [1.00, 7.00]  |\n|Missing                         |7 (0.0%)           |\n|**Born in NZ**                  |                   |\n|0                               |8510 (21.5%)       |\n|1                               |30670 (77.4%)      |\n|Missing                         |455 (1.1%)         |\n|**Conscientiousness**           |                   |\n|Mean (SD)                       |5.10 (1.06)        |\n|Median [Min, Max]               |5.23 [1.00, 7.00]  |\n|**Education Level**             |                   |\n|no_qualification                |1003 (2.5%)        |\n|cert_1_to_4                     |13801 (34.8%)      |\n|cert_5_to_6                     |4953 (12.5%)       |\n|university                      |10400 (26.2%)      |\n|post_grad                       |4220 (10.6%)       |\n|masters                         |3297 (8.3%)        |\n|doctorate                       |930 (2.3%)         |\n|Missing                         |1031 (2.6%)        |\n|**Employed**                    |                   |\n|0                               |8111 (20.5%)       |\n|1                               |31475 (79.4%)      |\n|Missing                         |49 (0.1%)          |\n|**Ethnicity**                   |                   |\n|euro                            |31454 (79.4%)      |\n|maori                           |4561 (11.5%)       |\n|pacific                         |971 (2.4%)         |\n|asian                           |2124 (5.4%)        |\n|Missing                         |525 (1.3%)         |\n|**Disability Status**           |                   |\n|Mean (SD)                       |0.223 (0.416)      |\n|Median [Min, Max]               |0 [0, 1.00]        |\n|Missing                         |745 (1.9%)         |\n|**Log Hours with Children**     |                   |\n|Mean (SD)                       |1.18 (1.61)        |\n|Median [Min, Max]               |0.0341 [0, 5.13]   |\n|Missing                         |1242 (3.1%)        |\n|**Log Hours Commuting**         |                   |\n|Mean (SD)                       |1.50 (0.832)       |\n|Median [Min, Max]               |1.61 [0, 4.40]     |\n|Missing                         |1242 (3.1%)        |\n|**Log Hours Exercising**        |                   |\n|Mean (SD)                       |1.55 (0.846)       |\n|Median [Min, Max]               |1.61 [0, 4.40]     |\n|Missing                         |1242 (3.1%)        |\n|**Log Hours on Housework**      |                   |\n|Mean (SD)                       |2.14 (0.782)       |\n|Median [Min, Max]               |2.20 [0, 5.13]     |\n|Missing                         |1242 (3.1%)        |\n|**Log Household Income**        |                   |\n|Mean (SD)                       |11.4 (0.765)       |\n|Median [Min, Max]               |11.5 [0.685, 14.9] |\n|Missing                         |3067 (7.7%)        |\n|**Male**                        |                   |\n|0                               |24766 (62.5%)      |\n|1                               |14767 (37.3%)      |\n|Missing                         |102 (0.3%)         |\n|**Neuroticism**                 |                   |\n|Mean (SD)                       |3.49 (1.15)        |\n|Median [Min, Max]               |3.48 [1.00, 7.00]  |\n|Missing                         |10 (0.0%)          |\n|**Non-heterosexual**            |                   |\n|0                               |35100 (88.6%)      |\n|1                               |2562 (6.5%)        |\n|Missing                         |1973 (5.0%)        |\n|**NZ Deprivation Index**        |                   |\n|Mean (SD)                       |4.77 (2.73)        |\n|Median [Min, Max]               |4.05 [1.00, 10.0]  |\n|Missing                         |255 (0.6%)         |\n|**Occupational Prestige Index** |                   |\n|Mean (SD)                       |54.1 (16.5)        |\n|Median [Min, Max]               |54.0 [10.0, 90.0]  |\n|Missing                         |536 (1.4%)         |\n|**Openness**                    |                   |\n|Mean (SD)                       |4.96 (1.12)        |\n|Median [Min, Max]               |5.00 [1.00, 7.00]  |\n|Missing                         |3 (0.0%)           |\n|**Parent**                      |                   |\n|0                               |11539 (29.1%)      |\n|1                               |27776 (70.1%)      |\n|Missing                         |320 (0.8%)         |\n|**Has Partner**                 |                   |\n|Mean (SD)                       |0.752 (0.432)      |\n|Median [Min, Max]               |1.00 [0, 1.00]     |\n|Missing                         |1244 (3.1%)        |\n|**Political Conservatism**      |                   |\n|Mean (SD)                       |3.59 (1.38)        |\n|Median [Min, Max]               |3.97 [1.00, 7.00]  |\n|Missing                         |2682 (6.8%)        |\n|**Major Religions**             |                   |\n|not_rel                         |24886 (62.8%)      |\n|anglican                        |2087 (5.3%)        |\n|buddist                         |332 (0.8%)         |\n|catholic                        |3123 (7.9%)        |\n|christian_nfd                   |4534 (11.4%)       |\n|christian_others                |1738 (4.4%)        |\n|hindu                           |206 (0.5%)         |\n|jewish                          |80 (0.2%)          |\n|muslim                          |90 (0.2%)          |\n|presby_cong_reform              |875 (2.2%)         |\n|the_others                      |1068 (2.7%)        |\n|Missing                         |616 (1.6%)         |\n|**Religious Identification**    |                   |\n|Mean (SD)                       |2.36 (2.18)        |\n|Median [Min, Max]               |1.00 [1.00, 7.00]  |\n|Missing                         |1050 (2.6%)        |\n|**Rural Classification**        |                   |\n|High Urban Accessibility        |24406 (61.6%)      |\n|Medium Urban Accessibility      |7431 (18.7%)       |\n|Low Urban Accessibility         |4818 (12.2%)       |\n|Remote                          |2241 (5.7%)        |\n|Very Remote                     |486 (1.2%)         |\n|Missing                         |253 (0.6%)         |\n|**Sample Frame Opt-In**         |                   |\n|0                               |38485 (97.1%)      |\n|1                               |1150 (2.9%)        |\n|**Short Form Health**           |                   |\n|Mean (SD)                       |5.05 (1.17)        |\n|Median [Min, Max]               |5.04 [1.00, 7.00]  |\n|Missing                         |6 (0.0%)           |\n|**Smoker**                      |                   |\n|0                               |35771 (90.3%)      |\n|1                               |2880 (7.3%)        |\n|Missing                         |984 (2.5%)         |\n\nDemographic statistics for New Zealand Attitudes and Values Cohort: {baseline_wave_glued}.\n:::\n\n### Sample Statistics: Exposure Variable {#appendix-exposure}\n\n::: {#tbl-appendix-exposures}\n\n|                          |2018              |2019              |\n|:-------------------------|:-----------------|:-----------------|\n|                          |(N=39635)         |(N=39635)         |\n|**Extraversion**          |                  |                  |\n|Mean (SD)                 |3.91 (1.20)       |3.86 (1.19)       |\n|Median [Min, Max]         |3.96 [1.00, 7.00] |3.79 [1.00, 7.00] |\n|Missing                   |0 (0%)            |11117 (28.0%)     |\n|**Extraversion (binary)** |                  |                  |\n|[1.0,4.0]                 |21138 (53.3%)     |15637 (39.5%)     |\n|(4.0,7.0]                 |18497 (46.7%)     |12881 (32.5%)     |\n|Missing                   |0 (0%)            |11117 (28.0%)     |\n\nDemographic statistics for New Zealand Attitudes and Values Cohort waves 2018.\n:::\n\n{{< pagebreak >}}\n\n### Sample Statistics: Outcome Variables {#appendix-outcomes}\n\n::: {#tbl-appendix-outcomes}\n\n|                              |2018              |2020              |Overall           |\n|:-----------------------------|:-----------------|:-----------------|:-----------------|\n|                              |(N=39635)         |(N=39635)         |(N=79270)         |\n|**Social Belonging**          |                  |                  |                  |\n|Mean (SD)                     |5.14 (1.07)       |5.06 (1.09)       |5.11 (1.08)       |\n|Median [Min, Max]             |5.31 [1.00, 7.00] |5.05 [1.00, 7.00] |5.30 [1.00, 7.00] |\n|Missing                       |7 (0.0%)          |13278 (33.5%)     |13285 (16.8%)     |\n|**Anxiety**                   |                  |                  |                  |\n|Mean (SD)                     |1.21 (0.774)      |1.17 (0.756)      |1.19 (0.767)      |\n|Median [Min, Max]             |1.00 [0, 4.00]    |1.00 [0, 4.00]    |1.00 [0, 4.00]    |\n|Missing                       |51 (0.1%)         |13275 (33.5%)     |13326 (16.8%)     |\n|**Depression**                |                  |                  |                  |\n|Mean (SD)                     |0.584 (0.751)     |0.550 (0.723)     |0.571 (0.740)     |\n|Median [Min, Max]             |0.333 [0, 4.00]   |0.333 [0, 4.00]   |0.333 [0, 4.00]   |\n|Missing                       |54 (0.1%)         |13273 (33.5%)     |13327 (16.8%)     |\n|**Life Satisfaction**         |                  |                  |                  |\n|Mean (SD)                     |5.30 (1.20)       |5.25 (1.23)       |5.28 (1.21)       |\n|Median [Min, Max]             |5.50 [1.00, 7.00] |5.50 [1.00, 7.00] |5.50 [1.00, 7.00] |\n|Missing                       |260 (0.7%)        |13560 (34.2%)     |13820 (17.4%)     |\n|**Hours of Exercise (log)**   |                  |                  |                  |\n|Mean (SD)                     |1.55 (0.846)      |1.63 (0.839)      |1.58 (0.844)      |\n|Median [Min, Max]             |1.61 [0, 4.40]    |1.78 [0, 4.40]    |1.61 [0, 4.40]    |\n|Missing                       |1242 (3.1%)       |13770 (34.7%)     |15012 (18.9%)     |\n|Meaning: Purpose              |                  |                  |                  |\n|Mean (SD)                     |5.20 (1.41)       |5.15 (1.44)       |5.18 (1.42)       |\n|Median [Min, Max]             |5.05 [1.00, 7.00] |5.04 [1.00, 7.00] |5.04 [1.00, 7.00] |\n|Missing                       |1010 (2.5%)       |13650 (34.4%)     |14660 (18.5%)     |\n|Meaning: Sense                |                  |                  |                  |\n|Mean (SD)                     |5.71 (1.22)       |5.71 (1.19)       |5.71 (1.20)       |\n|Median [Min, Max]             |5.99 [1.00, 7.00] |5.99 [1.00, 7.00] |5.99 [1.00, 7.00] |\n|Missing                       |128 (0.3%)        |13162 (33.2%)     |13290 (16.8%)     |\n|**Neighbourhood Community**   |                  |                  |                  |\n|Mean (SD)                     |4.19 (1.66)       |4.38 (1.57)       |4.27 (1.63)       |\n|Median [Min, Max]             |4.03 [1.00, 7.00] |4.95 [1.00, 7.00] |4.04 [1.00, 7.00] |\n|Missing                       |212 (0.5%)        |13202 (33.3%)     |13414 (16.9%)     |\n|**Personal Well-being Index** |                  |                  |                  |\n|Mean (SD)                     |7.09 (1.66)       |7.18 (1.63)       |7.12 (1.65)       |\n|Median [Min, Max]             |7.29 [0, 10.0]    |7.47 [0, 10.0]    |7.46 [0, 10.0]    |\n|Missing                       |41 (0.1%)         |13120 (33.1%)     |13161 (16.6%)     |\n|**Rumination**                |                  |                  |                  |\n|Mean (SD)                     |0.853 (1.00)      |0.797 (0.959)     |0.831 (0.987)     |\n|Median [Min, Max]             |0.955 [0, 4.00]   |0.0495 [0, 4.00]  |0.953 [0, 4.00]   |\n|Missing                       |135 (0.3%)        |13335 (33.6%)     |13470 (17.0%)     |\n|**Self Esteem**               |                  |                  |                  |\n|Mean (SD)                     |5.14 (1.28)       |5.13 (1.27)       |5.14 (1.28)       |\n|Median [Min, Max]             |5.34 [1.00, 7.00] |5.34 [1.00, 7.00] |5.34 [1.00, 7.00] |\n|Missing                       |11 (0.0%)         |13280 (33.5%)     |13291 (16.8%)     |\n|**Social Support**            |                  |                  |                  |\n|Mean (SD)                     |5.95 (1.12)       |5.94 (1.12)       |5.95 (1.12)       |\n|Median [Min, Max]             |6.30 [1.00, 7.00] |6.29 [1.00, 7.00] |6.30 [1.00, 7.00] |\n|Missing                       |30 (0.1%)         |13112 (33.1%)     |13142 (16.6%)     |\n\nOutcome variables measured at {baseline_wave_glued} and {outcome_wave}\n:::\n\n{{< pagebreak >}}\n\n## Appendix C: Transition Matrix to Check The Positivity Assumption {#appendix-transition}\n\n\n::: {#tbl-transition .cell tbl-cap='Transition Matrix Showing Change'}\n\n|From / To | State 0| State 1| Total|\n|:---------|-------:|-------:|-----:|\n|State 0   |   17572|    2271| 19843|\n|State 1   |    2400|    6275|  8675|\n:::\n\n\nThese transition matrices capture shifts in states between consecutive waves. Each cell shows the count of individuals transitioning from one state to another. Rows are the initial state (From), columns the subsequent state (To). **Diagonal entries** (in **bold**) mark those who stayed in the same state.\n\n{{< pagebreak >}}\n\n## Appendix D: RATE AUTOC and RATE Qini {#appendix-rate}\n\n\n\n\n\nRefer to [Appendix D](#appendix-cate-validation) for details.\n\n##### RATE AUTOC RESULTS\n\n### Evidence for heterogeneous treatment effects (policy = treat best responders) using AUTOC\n\nAUTOC uses logarithmic weighting to focus treatment on top responders.\n\nNote: The following outcomes were inverted during preprocessing because higher values of the exposure correspond to worse outcomes: Anxiety, Depression, Rumination.\n\nPositive RATE estimates for: **Hours of Exercise (log)**.\n\nEstimates (**Hours of Exercise (log)**: 0.084 (95% CI 0.035, 0.133)) show robust heterogeneity.\n\nNegative RATE estimates for: Neighbourhood Community.\n\nEstimates (Neighbourhood Community: -0.076 (95% CI -0.137, -0.015)) caution against CATE prioritisation.\n\nFor outcomes with adjusted p-values not meeting the FDR threshold of q = 0.20 (Meaning: Sense, Anxiety (reversed), Rumination (reversed), Self Esteem, Social Support, Life Satisfaction, Meaning: Purpose, Depression (reversed), Social Belonging, Personal Well-being Index), evidence is inconclusive.\n\n<!-- only include autoc plots if they exist -->\n\n::: {.cell}\n\n:::\n\n\n{{< pagebreak >}}\n\n## Appendix E: Estimating and Interpreting Heterogeneous Treatment Effects with GRF {#appendix-explain-grf}\n\n\n\n{{< pagebreak >}}\n\n## Appendix F: Strengths and Limitations of Causal Forests {#appendix-strengths}\n\n\n\n{{< pagebreak >}}\n\n## References {.appendix-refs}",
    "supporting": [
      "new_initial_quarto_document_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}