{
  "hash": "ea4dc557f413d9af72d226883a1f4893",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Your Title\"\nabstract: |\n\n  **Background**: (Brief few sentences)\n  **Objectives**: \n    1. Estimate the causal effect of YOUR EXPOSURE on YOUR OUTCOMES measured one year later.\n    2. Evaluate whether these effects vary across the population.\n    3. Provide policy guidance on which individuals might benefit most.\n  **Method**: We conducted a three-wave retrospective cohort study (waves XX-XXX, October XXXX--October XXXX) using data from the New Zealand Attitudes and Values Study, a nationally representative panel. Participants were eligible if they participated in the NZAVS in the baseline wave (XXXX, were under the age of 62, and were employed > 20 hours per week. We defined the exposure as (XXXX  > NUMBER on a 1-7 Likert Scale (1 = yes, 0 = no)). To address attrition, we applied inverse probability of censoring weights; to improve external validity, we applied weighted to the population distribution of Age, Ethnicity, and Gender. We computed expected mean outcomes for the population in each exposure condition (high XXXX/low XXXXX). Under standard causal assumptions of unconfoundedness, the contrast provides an unbiased average treatment effect. We then used causal forests to detect heterogeneity in these effects and employed policy tree algorithms to identify individuals (\"strong responders\") likely to experience the greatest benefits.\n  **Results**:   Increasing XXXXX leads to XXXXX. Heterogeneous responses to (e.g. *Forgiveness*, *Personal Well-Being*, and *Life-Satisfaction*...) reveal structural variability in subpopulations...\n  **Implications**: (Brief few sentences)\n  **Keywords**: *Causal Inference*;  *Cross-validation*; *Distress*; *Employment*; *Longitudinal*; *Machine sLearning*; *Religion*; *Semi-parametric*; *Targeted Learning*.\nauthor: \n  - name: YOUR NAME\n    affiliation: Victoria University of Wellington, New Zealand\n    email: XXXXX\n    corresponding: yes\nkeywords: [Causal Inference, Cross-validation,...]\neditor_options: \n  chunk_output_type: console\ndate: \"last-modified\"\nfontfamily: libertinus\nbibliography: references.bib\ncsl: apa7.csl\nformat:\n  pdf:\n    pdf-engine: lualatex\n    sanitise: true\n    keep-tex: true\n    link-citations: true\n    colorlinks: true\n    documentclass: article\n    classoption: [\"single column\"]\n    lof: false\n    lot: false\n    geometry:\n      - top=30mm\n      - left=25mm\n      - heightrounded\n      - headsep=22pt\n      - headheight=11pt\n      - footskip=33pt\n      - ignorehead\n      - ignorefoot\n    header-includes:\n      - \\let\\oldtabular\\tabular\n      - \\renewcommand{\\tabular}{\\small\\oldtabular}\n      - \\setlength{\\tabcolsep}{4pt}  # adjust this value as needed\nexecute:\n  echo: false\n  warning: false\n  include: true\n  eval: true\n---\n\n\n\n{{< pagebreak >}}\n\n## Method\n\n### Sample\n\nData were collected as part of the New Zealand Attitudes and Values Study (NZAVS), an annual longitudinal national probability panel assessing New Zealand residents’ social attitudes, personality, ideology, and health outcomes. The panel began in 2009 and has since expanded to include over fifty researchers, with responses from 40,000 participants to date. The study operates independently of political or corporate funding and is based at a university. It employs prize draws to incentivise participation. The NZAVS tends to slightly under-sample males and individuals of Asian descent and to over-sample females and Māori (the Indigenous people of New Zealand). To enhance the representativeness of our sample population estimates for the target population of New Zealand, we apply census-based survey weights that adjust for age, gender, and ethnicity (New Zealand European, Asian, Māori, Pacific) [@sibley2021]. For more information about the NZAVS, visit: [OSF.IO/75SNB](https://doi.org/10.17605/OSF.IO/75SNB).\n\n### Target Population\n\nThe target population for this study comprises New Zealand residents as represented in the 2018 of the New Zealand Attitudes and Values Study (NZAVS) during the years 2018 weighted by New Zealand Census weights for age, gender, and ethnicity (refer to @sibley2021). The NZAVS is a national probability study designed to reflect the broader New Zealand population accurately. Despite its comprehensive scope, the NZAVS has some limitations in its demographic representation. Notably, it tends to under-sample males and individuals of Asian descent while over-sampling females and Māori (the indigenous peoples of New Zealand). To address these disparities and enhance the accuracy of our findings, we apply New Zealand Census survey weights to the sample data.\n\n### Eligibility Criteria\n\nTo be included in the analysis of this study, participants needed to participate in the 2018 of the study and respond to the baseline measure of Extraversion.\n\nParticipants may have been lost to follow-up at the end of the study if they met eligibility criteria at 2018. We adjusted for attrition and non-response using censoring weights, described below.\n\nA total of 39,635 individuals met these criteria and were included in the study.\n\n### Average Treatment Effect\n\nResearchers often want to know what might happen if we could change (or 'intervene on') a particular variable for everyone in a study—much like testing a new treatment in a randomised trial. Because we cannot always run an actual trial, we imagine a **target trial** [@hernan2016], a hypothetical experiment that clarifies exactly which cause-and-effect question we are trying to answer.\n\nHere, we ask:\n\n  > 'How would the outcomes of interest change if, for everyone in the population, we set the exposure to **>4, scale range 1-7**, compared with setting it to **<=4, scale range 1-7**, given each individual’s characteristics?'\n\nThus we compare two scenarios:\n\n1. **1**: Everyone receives exposure level >4, scale range 1-7.\n2. **0**: Everyone receives exposure level <=4, scale range 1-7.\n\nThe difference between these two population means is the **Average Treatment Effect (ATE)**.  Because we evaluate several outcomes, ATE confidence intervals were corrected for multiplicity with bonferroni at $\\alpha$ = 0.05.\n\nBy combining time-series data with a rich baseline covariate set, we may, under the identifications assumptions described below, separate the causal effects of the exposure from spurious associations. Measuring demographics, personality traits, and other background factors at baseline helps ensure that, conditional on those covariates, assignment to the two exposure levels is 'as good as random.'  (See Appendix [D](#appendix-assumptions_grf) for a full statement of the required assumptions.)\n\n\n### Heterogeneous Treatment Effects and Treatment Policies\n\nAfter estimating the overall average treatment effect (ATE) for the population, we turn to the question of whether different people respond differently. We investigate effect modifiers (or moderators)—factors that make the intervention more or less effective for certain subgroups—by estimating the Conditional Average Treatment Effect (CATE) using a causal forest approach. While the ATE reflects the overall impact, the CATE reveals how that impact can vary across individuals with different baseline characteristics. We denote the individual-level estimated treatment effect as $\\hat{\\tau}(x)$, which represents the predicted benefit for an individual with covariates $x$. A notable advantage of causal forests is that we do not have to specify potential moderators in advance; the algorithm uncovers them automatically. We can also apply search algorithms to derive priority treatment rules that target the intervention to those most likely to benefit.\n\nFirst, we standardised effect directions by inverting outcomes where lower scores were preferable so that positive values always indicated improvement. Specifically, we inverted Anxiety, Depression, Rumination.\n\nNext, to reduce overfitting and separate real heterogeneity from noise, we split the data into training and validation folds (70/30).  A causal forest trained on the first fold produced out-of-sample CATE predictions on the second.  We then computed Rank-Weighted Average Treatment Effect (RATE) metrics—AUTOC and Qini—which quantify the gain from targeting the highest-ranked individuals [@grf2024; @wager2018].  Their *p*-values were corrected with Benjamini–Hochberg false-discovery-rate adjustment at q = 0.1 to control the exploratory false-discovery rate [@benjamini1995controlling].  Where heterogeneity remained reliable, we fitted depth-2 policy trees [@policytree_package_2024; @athey2021; @athey_2021_policy_tree_econometrica] to distil transparent 'treat-if' rules (e.g., *treat if baseline score > X*).\n\nAll heterogeneity steps—calibration tests, RATE, Qini curves, and policy-tree learning—were implemented in R with **grf** [@grf2024], **policytree** [@policytree_package_2024], using graphical and summary functions from **margot** [@margot2024].  This workflow identifies individualised effects, quantifies the policy value of targeting, and delivers practical decision rules.  See [Appendix D](#appendix-explain-grf) for full methodological details.\n\n### Exposure Indicator\n\n\nThe New Zealand Attitudes and Values Study assesses Extraversion using the following question:\n\n\nMini-IPIP6 Extraversion dimension: (i) I am the life of the party. (ii) I don't talk a lot. (r) (iii) I keep in the background. (r) (iv) I talk to a lot of different people at parties.(Refer to [Appendix A](#appendix-measures)).\n\n### Causal Identification Assumptions\n\nThis study relies on the following identification assumptions for estimating the causal effect of Extraversion:\n\n1. **Consistency**: the observed outcome under the observed Extraversion is equal to the potential outcome under that exposure level. As part of consistency, we assume no interference: the potential outcomes for one individual are not affected by the Extraversion status of other individuals.\n\n2. **No unmeasured confounding**: all variables that affect both Extraversion and the outcome have been measured and accounted for in the analysis.\n\n3. **Positivity**: there is a non-zero probability of receiving each level of Extraversion for every combination of values of Extraversion and confounders in the population. Positivity is the only fundamental casual assumption that can be evaluated with data (refer to [Appendix E](#appendix-positivity)).\n\n### Confounding Control\n\nTo manage confounding in our analysis, we implement @vanderweele2019's *modified disjunctive cause criterion* by following these steps:\n\n1. **Identified all common causes** of both the treatment and outcomes.\n2. **Excluded instrumental variables** that affect the exposure but not the outcome. Instrumental variables do not contribute to controlling confounding and can reduce the efficiency of the estimates.\n3. **Included proxies for unmeasured confounders** affecting both exposure and outcome. According to the principles of d-separation @pearl2009a, using proxies allows us to control for their associated unmeasured confounders indirectly.\n4. **Controlled for baseline exposure** and **baseline outcome**. Both are used as proxies for unmeasured common causes, enhancing the robustness of our causal estimates, refer to @vanderweele2020.\n\n### Statistical Estimation\n\nWe estimate heterogeneous treatment effects with Generalized Random Forests (GRF) [@grf2024]. GRF extends random forests for causal inference by focusing on conditional average treatment effects (CATE). It handles complex interactions and non-linearities without explicit model specification, and it provides 'honest' estimates by splitting data between model-fitting and inference. GRF is doubly robust because it remains consistent if either the outcome model or the propensity model is correct. We evaluate policies with the `policytree` package [@policytree_package_2024; @athey_2021_policy_tree_econometrica] and visualise results with `margot` [@margot2024]. (Refer to [Appendix D](#appendix-explain-grf) for a detailed explanation of our approach.)\n\n### Missing Data\n\nThe GRF package accepts missing values at baseline. To obtain valid inference for missing responses we computed inverse probability of censoring weights for censoring of the exposure, given that systematic censoring following the baseline wave may lead to selection bias that limit generalistion to the baseline target population [@bulbulia2024wierd]. See [Appendix D](#appendix-explain-grf).\n\n### Sensitivity Analysis\nWe perform sensitivity analyses using the E-value metric [@vanderweele2017; @linden2020EVALUE]. The E-value represents the minimum association strength (on the risk-ratio scale) that an unmeasured confounder would need with both exposure and outcome—after adjusting for measured covariates—to explain away the observed association [@vanderweele2020; @linden2020EVALUE]. Confidence intervals for each E-value were derived from the multiplicity-adjusted confidence intervals of the corresponding coefficient estimates (bonferroni, α = 0.05), so the sensitivity analysis obeys the same error-control framework as the main results.\n\n\n{{< pagebreak >}}\n\n## Results\n\n### Average Treatement Effects\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Average Treatment Effects on Multi-dimensional Wellbeing](initial_quarto_document_files/figure-pdf/fig-ate-1.pdf){#fig-ate}\n:::\n:::\n\n\n{{< pagebreak >}}\n\n\n::: {#tbl-outcomes .cell tbl-cap='Average Treatment Effects on Multi-dimensional Wellbeing'}\n::: {.cell-output-display}\n\n\n|Outcome                       |ATE        |2.5 %      |97.5 %     |E-Value   |E-Value bound |\n|:-----------------------------|:----------|:----------|:----------|:---------|:-------------|\n|**Social Belonging**          |**0.125**  |**0.083**  |**0.167**  |**1.488** |**1.372**     |\n|**Neighbourhood Community**   |**0.119**  |**0.073**  |**0.165**  |**1.471** |**1.343**     |\n|**Social Support**            |**0.096**  |**0.052**  |**0.14**   |**1.407** |**1.277**     |\n|**Self Esteem**               |**0.087**  |**0.047**  |**0.127**  |**1.381** |**1.26**      |\n|**Meaning: Purpose**          |**0.095**  |**0.043**  |**0.147**  |**1.404** |**1.241**     |\n|**Meaning: Sense**            |**0.086**  |**0.033**  |**0.138**  |**1.378** |**1.208**     |\n|**Anxiety**                   |**-0.064** |**-0.107** |**-0.02**  |**1.312** |**1.159**     |\n|**Depression**                |**-0.057** |**-0.103** |**-0.011** |**1.29**  |**1.116**     |\n|**Personal Well-being Index** |**0.052**  |**0.011**  |**0.094**  |**1.274** |**1.11**      |\n|Rumination                    |-0.04      |-0.091     |0.01       |1.233     |1             |\n|Hours of Exercise (log)       |-0.032     |-0.088     |0.024      |1.204     |1             |\n|Life Satisfaction             |0.044      |0          |0.088      |1.247     |1             |\n\n\n:::\n:::\n\n\n\n\nConfidence intervals were adjusted for multiple comparisons using bonferroni correction ($\\alpha$ = 0.05). E‑values were also adjusted using bonferroni correction ($\\alpha$ = 0.05).\n\nThe following outcomes showed reliable causal evidence (E‑value lower bound > 1.2):\n- Social Belonging: 0.125(0.064,0.186); on the original scale, 0.136 (0.07,0.203).  E‑value bound = 1.311\n- Neighbourhood Community: 0.119(0.052,0.186); on the original scale, 0.187 (0.082,0.292).  E‑value bound = 1.273\n- Social Support: 0.096(0.032,0.16); on the original scale, 0.107 (0.036,0.179).  E‑value bound = 1.203\n\n\n\n\n{{< pagebreak >}}\n\n### Heterogeneous Treatment Effects \n\n#### RATE AUTOC and RATE Qini\n\n#### Rate Test\n\nThe RATE metric shows how much extra gain (or avoided loss) we achieve by **targeting** instead of treating everyone identically.\n\n**Technical note**: In code we always set `policy = \"treat_best\"`; for harmful exposures this is interpreted as *'treat-those-most-sensitive'* (i.e., prioritise protection or withholding).\n\n* **Beneficial exposure:** we rank by positive CATEs and deliver the exposure to those predicted to **benefit most**.\n* **Detrimental exposure:** we rank by increasingly **positive** CATEs (more predicted harm) and identify those who should be protected or withheld from the exposure.\n\nEither way, a larger **absolute** RATE shows that a CATE-based targeting rule 'outperforms' a one-size-fits-all policy—by boosting outcomes for beneficial exposures or -- in the case where we are explore sensitivity to harm -- evaluating increasing harms for detrimental ones.\n\nRecall we flipped Anxiety, Depression, Rumination so **'higher' always tracks the analysis goal: higher = more benefit for beneficial exposures, higher = more harm for detrimental exposures.**\n\nBecause we test several outcomes, RATE *p*-values are adjusted with Benjamini–Hochberg false-discovery-rate adjustment (q = 0.1) before we decide whether heterogeneity is actionable.\n\n### Comparison of targeting operating characteristic (TOC) by rank average treatment effect (RATE): AUTOC vs QINI\n\nWe applied two TOC by RATE methods to the same causal-forest \\tau(x) estimates:\n\n- **AUTOC** intensifies focus on top responders via logarithmic weighting.\n\n- **QINI** balances effect size and prevalence via linear weighting.\n\nWe treated the RATE analysis as exploratory. All 12 outcomes were prespecified. To flag promising signals we controlled the false discovery rate at q=0.20.\n\nWhen QINI and AUTOC disagree on positive RATE (only AUTOC yields a positive RATE for **Hours of Exercise (log)**; only QINI yields a positive RATE for Meaning: Sense), choose **QINI** to maximise overall benefit or **AUTOC** to focus on top responders.\n\nRefer to [Appendix E](#appendix-cate-validation) for details.\n\n\n\n##### RATE AUTOC Results\n\n### Evidence for heterogeneous treatment effects (policy = treat best responders) using AUTOC\n\nAUTOC uses logarithmic weighting to focus treatment on top responders. We treated the RATE analysis as exploratory. All 12 outcomes were prespecified. To flag promising signals we controlled the false discovery rate at q=0.20.\n\nPositive RATE estimates for: **Hours of Exercise (log)**.\n\nEstimates (**Hours of Exercise (log)**: 0.065 (95% CI 0.018, 0.112)) show robust heterogeneity.\n\nFor outcomes with adjusted p-values not meeting the FDR threshold of q = 0.20 (Meaning: Sense, Rumination, Anxiety, Personal Well-being Index, Self Esteem, Social Belonging, Social Support, Life Satisfaction, Meaning: Purpose, Depression, Neighbourhood Community), evidence is inconclusive.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![RATE AUTOC Graphs](initial_quarto_document_files/figure-pdf/fig-rate-1-1.pdf){#fig-rate-1}\n:::\n:::\n\n\n@fig-rate-1 presents the RATE AUTOC curve for Hours of Exercise (log)\n\n##### RATE Qini Results\n\n### Evidence for heterogeneous treatment effects (policy = treat best responders) using QINI\n\nQINI uses linear weighting to balance effect size and prevalence. We treated the RATE analysis as exploratory. All 12 outcomes were prespecified. To flag promising signals we controlled the false discovery rate at q=0.20.\n\nPositive RATE estimates for: **Meaning: Sense**.\n\nEstimates (**Meaning: Sense**: 0.020 (95% CI 0.002, 0.038)) show robust heterogeneity.\n\nNegative RATE estimates for: Neighbourhood Community.\n\nEstimates (Neighbourhood Community: -0.026 (95% CI -0.042, -0.010)) caution against CATE prioritisation.\n\nFor outcomes with adjusted p-values not meeting the FDR threshold of q = 0.20 (Hours of Exercise (log), Personal Well-being Index, Anxiety, Self Esteem, Social Support, Life Satisfaction, Social Belonging, Rumination, Meaning: Purpose, Depression), evidence is inconclusive.\n\n\n#### QINI Curve Analysis\n\n#### Qini Curves\n\nThe Qini curve shows the cumulative **gain** as we expand a targeting rule down the CATE ranking.\n\n* **Beneficial exposure:** we add individuals from the top positive CATEs downward; the baseline is 'expose everyone.'\n* **Detrimental exposure:** we first flip outcome direction (so higher values represent **more harm**; see Anxiety, Depression, Rumination), then *add* the exposure starting with individuals whose CATEs show the **greated harm**, gradually including those predicted to be more resistant to harm; the baseline is 'expose everyone.'  The curve therefore quantifies the harm by when those most suceptible to harm are exposed.\n\nIf the Qini curve stays above its baseline, a targeted policy increases the outcome more than a one-size-fits-all alternative. (Outcome directions were flipped where needed—Anxiety, Depression, Rumination—so the positively valenced exposures always have positively valanced outcomes and negative exposures always have negatively valenced outcomes.)\n\nWe computed the cumulative benefits as we increase the treated fraction by prioritising conditional average treatment effects (CATE) at two different spend levels: 20% of a total budget and 50% of a total budget, where the contrast is no priority assignment. \n **Meaning Sense**\nAt 20% spend: CATE prioritisation is beneficial (diff: 0.04 [95% CI: 0.01, 0.07]). At 50 % spend: No reliable benefits from CATE prioritisation.\n\n@tbl-qini presents results for our Qini curve analysis at different spend rates.\n\n\n::: {#tbl-qini .cell tbl-cap='Qini Curve Results'}\n::: {.cell-output-display}\n\n\n|Model         |Spend 20%             |Spend 50%           |\n|:-------------|:---------------------|:-------------------|\n|Meaning Sense |**0.04 [0.01, 0.07]** |-0.00 [-0.06, 0.05] |\n\n\n:::\n:::\n\n\n@fig-qini-1 presents the Qini curve for Meaning: Sense\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Qini Graph](initial_quarto_document_files/figure-pdf/fig-qini-1-1.pdf){#fig-qini-1}\n:::\n:::\n\n\n\n{{< pagebreak >}}\n\n#### Decision Rules (Who is Most Sensitive to Treatment?)\n\n#### Policy Trees\n\nWe used policy trees [@policytree_package_2024; @athey2021; @athey_2021_policy_tree_econometrica] to find straightforward ‘if-then’ rules for who benefits most from treatment, based on participant characteristics. Because we flipped some measures, a higher predicted effect always means greater improvement. Policy trees can uncover small but important subgroups whose treatment responses stand out, even when the overall differences might be modest.\n\n        \n\n::: {.cell}\n::: {.cell-output-display}\n![Decision Tree: {glued_name_policy_1}](initial_quarto_document_files/figure-pdf/fig-policy-1-1.pdf){#fig-policy-1}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Decision Tree: {glued_name_policy_2}](initial_quarto_document_files/figure-pdf/fig-policy-2-1.pdf){#fig-policy-2}\n:::\n:::\n\n\n\n### Policy Tree Interpretations (depth 2)\n\nA shallow policy tree recommends actions based on two splits for depth=2, or one split for depth=1.\nWe trained on 50% of the data and evaluated on the rest.\n\n\n**Findings for log Hours Exercise:**\n\nSplit 1: Short Form Health ≤ -0.333.  Within that subgroup, split 2a: Belong ≤ -0.441, → **Control**; Belong > -0.441 → **Treated**.\n\nSplit 2: Short Form Health > -0.333.  Within that subgroup, split 2b: Lifesat ≤ -0.268, → **Control**; Lifesat > -0.268 → **Treated**.\n\n\n**Findings for Meaning Sense:**\n\nSplit 1: Alcohol Intensity ≤ -0.313.  Within that subgroup, split 2a: log Hours Commute ≤ -0.496, → **Control**; log Hours Commute > -0.496 → **Treated**.\n\nSplit 2: Alcohol Intensity > -0.313.  Within that subgroup, split 2b: Age ≤ 0.612, → **Treated**; Age > 0.612 → **Control**.\n \n\n## Discussion\n\n### Ethics\n\nThe University of Auckland Human Participants Ethics Committee reviews the NZAVS every three years. Our most recent ethics approval statement is as follows: The New Zealand Attitudes and Values Study was approved by the University of Auckland Human Participants Ethics Committee on 26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.\n\n### Author Statement\n\n\n### Acknowledgements\n\nThe New Zealand Attitudes and Values Study is supported by a grant from the Templeton Religious Trust (TRT0196; TRT0418). JB received support from the Max Plank Institute for the Science of Human History. The funders had no role in preparing the manuscript or deciding to publish it.\n\n### Data Availability\n\nThe data described in the paper are part of the New Zealand Attitudes and Values Study. Members of the NZAVS management team and research group hold full copies of the NZAVS data. A de-identified dataset containing only the variables analysed in this manuscript is available upon request from the corresponding author or any member of the NZAVS advisory board for replication or checking of any published study using NZAVS data. The code for the analysis can be found at [OSF link](https://osf.io/ab7cx/).\n\n\n\n{{< pagebreak >}}\n\n\n## Appendix A: Measures {#appendix-measures}\n\n\n### Measures \n\n####  Baseline Covariate Measures \n\n### Baseline Covariates\n\n#### Age\n\n*What is your date of birth?*\n\nWe asked participants' ages in an open-ended question (\"What is your age?\" or \"What is your date of birth\"). [@string_is Developed for the NZAVS.]\n\n#### Agreeableness\n\n*I sympathize with others' feelings.*\n*I am not interested in other people's problems.*\n*I feel others' emotions.*\n*I am not really interested in others (reversed).*\n\nMini-IPIP6 Agreeableness dimension: (i) I sympathize with others' feelings. (ii) I am not interested in other people's problems. (r) (iii) I feel others' emotions. (iv) I am not really interested in others. (r) [@sibley2011]\n\n#### Alcohol Frequency\n\n*\"How often do you have a drink containing alcohol?\"*\n\nParticipants could chose between the following responses: '(1 = Never - I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to 3 times a week, 5 = 4 or more times a week, 6 = Don't know)' [@Ministry_of_Health_2013]\n\n#### Alcohol Intensity\n\n*\"How many drinks containing alcohol do you have on a typical day when drinking alcohol? (number of drinks on a typical day when drinking)\"*\n\nParticipants responded using an open-ended box. [@Ministry_of_Health_2013]\n\n#### Social Belonging\n\n*Know that people in my life accept and value me.*\n*Feel like an outsider (reversed).*\n*Know that people around me share my attitudes and beliefs.*\n\nWe assessed felt belongingness with three items adapted from the Sense of Belonging Instrument (Hagerty & Patusky, 1995): (1) \"Know that people in my life accept and value me\"; (2) \"Feel like an outsider\"; (3) \"Know that people around me share my attitudes and beliefs\". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded. [@hagerty1995]\n\n#### Born in Nz\n\n*Where were you born? (please be specific, e.g., which town/city?)*\n\nCoded binary (1 = New Zealand; 0 = elsewhere.)\n [@string_is Developed for the NZAVS.]\n\n#### Conscientiousness\n\n*I get chores done right away.*\n*I like order.*\n*I make a mess of things.*\n*I often forget to put things back in their proper place.*\n\nMini-IPIP6 Conscientiousness dimension: (i) I get chores done right away. (ii) I like order. (iii) I make a mess of things. (r) (iv) I often forget to put things back in their proper place. (r) [@sibley2011]\n\n#### Education Level\n\n*What is your highest level of qualification?*\n\nWe asked participants, \"What is your highest level of qualification?\". We coded participans highest finished degree according to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with overseas school qualifications coded as Level 3, and all other ancillary categories coded as missing) [@string_is Developed for the NZAVS.]\n\n#### Employed\n\n*Are you currently employed (This includes self-employed of casual work)?*\n\nBinary response: (0 = No, 1 = Yes) [@string_is Stats NZ Census Question]\n\n#### Ethnicity\n\n*Which ethnic group(s) do you belong to?*\n\nCoded string: (1 = New Zealand European; 2 = Māori; 3 = Pacific; 4 = Asian) [@string_is NZ Census coding.]\n\n#### Disability Status\n\n*Do you have a health condition or disability that limits you and that has lasted for 6+ months?*\n\nWe assessed disability with a one-item indicator adapted from Verbrugge (1997). It asks, \"Do you have a health condition or disability that limits you and that has lasted for 6+ months?\" (1 = Yes, 0 = No). [@verbrugge1997]\n\n#### Log Hours with Children\n\n*Hours spent...looking after children.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Log Hours Commuting\n\n*Hours spent...travelling/commuting.*\n\nWe took the natural log of the response + 1. [@string_is Developed for the NZAVS.]\n\n#### Log Hours of Exercise\n\n*Hours spent...exercising/physical activity.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Log Hours on Housework\n\n*Hours spent...housework/cooking.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Log Household Income\n\n*Please estimate your total household income (before tax) for the year XXXX.*\n\nWe took the natural log of the response + 1. [@string_is Developed for the NZAVS.]\n\n#### Male\n\n*We asked participants’ gender in an open-ended question: \"what is your gender?\"*\n\nHere, we coded all those who responded as Male as 1, and those who did not as 0.\n [@fraser_coding_2020]\n\n#### Neuroticism\n\n*I have frequent mood swings.*\n*I am relaxed most of the time (reversed).*\n*I get upset easily.*\n*I seldom feel blue (reversed).*\n\nMini-IPIP6 Neuroticism dimension: (i) I have frequent mood swings. (ii) I am relaxed most of the time. (r) (iii) I get upset easily. (iv) I seldom feel blue. (r) [@sibley2011]\n\n#### Non Heterosexual\n\n*How would you describe your sexual orientation? (e.g., heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)*\n\nOpen-ended question, coded as binary (not heterosexual = 1). [@greaves2017diversity]\n\n#### Nz Deprivation Index\n\n*New Zealand Deprivation - Decile Index - Using 2018 Census Data*\n\nNumerical: (1-10) [@atkinson2019]\n\n#### Occupational Prestige Index\n\n*We assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13).*\n\nThis index uses the income, age, and education of a reference group, in this case, the 2013 New Zealand census, to calculate a score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant a NZSEI-13 score based on their occupation.\n [@fahy2017]\n\n#### Openness\n\n*I have a vivid imagination.*\n*I have difficulty understanding abstract ideas (reversed).*\n*I do not have a good imagination (reversed).*\n*I am not interested in abstract ideas (reversed).*\n\nMini-IPIP6 Openness to Experience dimension: (i) I have a vivid imagination. (ii) I have difficulty understanding abstract ideas. (r) (iii) I do not have a good imagination. (r) (iv) I am not interested in abstract ideas. (r) [@sibley2011]\n\n#### Parent\n\n*If you are a parent, in which year was your eldest child born?*\n\nParents were coded as 1, while the others were coded as 0.\n [@Developed for the NZAVS.]\n\n#### Has Partner\n\n*What is your relationship status? (e.g., single, married, de-facto, civil union, widowed, living together, etc.)*\n\nCoded as binary (has partner = 1). [@string_is Developed for the NZAVS.]\n\n#### Political Conservatism\n\n*Please rate how politically liberal versus conservative you see yourself as being.*\n\nOrdinal response: (1 = Extremely Liberal, 7 = Extremely Conservative)\n [@jost_end_2006-1]\n\n#### Religious Identification\n\n*How important is your religion to how you see yourself?*\n\nOrdinal response: (1 = Not Important, 7 = Very Important) [@string_is Developed for the NZAVS.]\n\n#### Rural Classification\n\n*High Urban Accessibility = 1, Medium Urban Accessibility = 2, Low Urban Accessibility  = 3, Remote = 4, Very Remote = 5.*\n\n\"Participants residence locations were coded according to a five-level ordinal categorisation ranging from Urban to Rural.\" [@whitehead2023unmasking]\n\n#### Sample Frame Opt in\n\n*Participant was not randomly sampled from the New Zealand Electoral Roll.*\n\nCode string (Binary): (0 = No, 1 = Yes) [@string_is Developed for the NZAVS.]\n\n#### Short Form Health\n\n*In general, would you say your health is...*\n\nOrdinal response: (1 = Poor, 7 = Excellent) [@instrument1992mos]\n\n#### Smoker\n\n*Do you currently smoke tobacco cigarettes?*\n\nBinary smoking indicator (0 = No, 1 = Yes). [@string_is Developed for NZAVS.]\n\n#### Exposure Measures\n\n### Exposure Variable\n\n#### Extraversion\n\n*I am the life of the party.*\n*I don't talk a lot (reversed).*\n*I keep in the background (reversed).*\n*I talk to a lot of different people at parties.*\n\nMini-IPIP6 Extraversion dimension: (i) I am the life of the party. (ii) I don't talk a lot. (r) (iii) I keep in the background. (r) (iv) I talk to a lot of different people at parties. [@sibley2011]\n\n#### Outcome Measures\n\n### Outcome Variables\n\n#### Social Belonging\n\n*Know that people in my life accept and value me.*\n*Feel like an outsider (reversed).*\n*Know that people around me share my attitudes and beliefs.*\n\nWe assessed felt belongingness with three items adapted from the Sense of Belonging Instrument (Hagerty & Patusky, 1995): (1) \"Know that people in my life accept and value me\"; (2) \"Feel like an outsider\"; (3) \"Know that people around me share my attitudes and beliefs\". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded. [@hagerty1995]\n\n#### Anxiety\n\n*During the past 30 days, how often did...you feel restless or fidgety?*\n*During the past 30 days, how often did...you feel that everything was an effort?*\n*During the past 30 days, how often did...you feel nervous?*\n\nOrdinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2= Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time) [@kessler2002]\n\n#### Depression\n\n*During the past 30 days, how often did...you feel hopeless?*\n*During the past 30 days, how often did...you feel so depressed that nothing could cheer you up?*\n*During the past 30 days, how often did...you feel you feel restless or fidgety?*\n\nOrdinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2= Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time) [@kessler2002]\n\n#### Life Satisfaction\n\n*I am satisfied with my life.*\n*In most ways my life is close to ideal.*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@diener1985a]\n\n#### Log Hours of Exercise\n\n*Hours spent...exercising/physical activity.*\n\nWe took the natural log of the response + 1. [@sibley2011]\n\n#### Meaning Purpose\n\n*My life has a clear sense of purpose*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@steger_meaning_2006]\n\n#### Meaning Sense\n\n*I have a good sense of what makes my life meaningful.*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@steger_meaning_2006]\n\n#### Neighbourhood Community\n\n*I feel a sense of community with others in my local neighbourhood.*\n\nOrdinal response (1 = Strongly Disagree to 7 = Strongly Agree). [@sengupta2013]\n\n#### Personal Well Being Index\n\nno information available for this variable.\n\n#### Rumination\n\n*During the last 30 days, how often did...you have negative thoughts that repeated over and over?*\n\nOrdinal responses: 0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time. [@nolen-hoeksema_effects_1993]\n\n#### Self Esteem\n\n*On the whole am satisfied with myself.*\n*Take a positive attitude toward myself.*\n*Am inclined to feel that I am a failure (reversed).*\n\nOrdinal response (1 = Very inaccurate to 7 = Very accurate). [@Rosenberg1965]\n\n#### Social Support\n\n*There are people I can depend on to help me if I really need it.*\n*There is no one I can turn to for guidance in times of stress (reversed).*\n*I know there are people I can turn to when I need help.*\n\nOrdinal response: (1 = Strongly Disagree, 7 = Strongly Agree) [@cutrona1987]\n\n\n{{< pagebreak >}}\n\n## Appendix B: Sample Characteristics {#appendix-sample}\n\n####  Sample Statistics: Baseline Covariates\n\n\n@tbl-appendix-baseline presents sample demographic statistics.\n\n::: {#tbl-appendix-baseline}\n\n|                                |2018               |\n|:-------------------------------|:------------------|\n|                                |(N=39635)          |\n|**Age**                         |                   |\n|Mean (SD)                       |48.5 (13.9)        |\n|Median [Min, Max]               |51.0 [18.0, 99.0]  |\n|**Agreeableness**               |                   |\n|Mean (SD)                       |5.35 (0.988)       |\n|Median [Min, Max]               |5.47 [1.00, 7.00]  |\n|Missing                         |9 (0.0%)           |\n|**Alcohol Frequency**           |                   |\n|Mean (SD)                       |2.16 (1.34)        |\n|Median [Min, Max]               |2.00 [0, 5.00]     |\n|Missing                         |1342 (3.4%)        |\n|**Alcohol Intensity**           |                   |\n|Mean (SD)                       |2.15 (2.09)        |\n|Median [Min, Max]               |2.00 [0, 15.0]     |\n|Missing                         |2348 (5.9%)        |\n|**Belong**                      |                   |\n|Mean (SD)                       |5.14 (1.07)        |\n|Median [Min, Max]               |5.31 [1.00, 7.00]  |\n|Missing                         |7 (0.0%)           |\n|**Born in NZ**                  |                   |\n|0                               |8510 (21.5%)       |\n|1                               |30670 (77.4%)      |\n|Missing                         |455 (1.1%)         |\n|**Conscientiousness**           |                   |\n|Mean (SD)                       |5.10 (1.06)        |\n|Median [Min, Max]               |5.23 [1.00, 7.00]  |\n|**Education Level**             |                   |\n|no_qualification                |1003 (2.5%)        |\n|cert_1_to_4                     |13801 (34.8%)      |\n|cert_5_to_6                     |4953 (12.5%)       |\n|university                      |10400 (26.2%)      |\n|post_grad                       |4220 (10.6%)       |\n|masters                         |3297 (8.3%)        |\n|doctorate                       |930 (2.3%)         |\n|Missing                         |1031 (2.6%)        |\n|**Employed**                    |                   |\n|0                               |8111 (20.5%)       |\n|1                               |31475 (79.4%)      |\n|Missing                         |49 (0.1%)          |\n|**Ethnicity**                   |                   |\n|euro                            |31454 (79.4%)      |\n|maori                           |4561 (11.5%)       |\n|pacific                         |971 (2.4%)         |\n|asian                           |2124 (5.4%)        |\n|Missing                         |525 (1.3%)         |\n|**Disability Status**           |                   |\n|Mean (SD)                       |0.223 (0.416)      |\n|Median [Min, Max]               |0 [0, 1.00]        |\n|Missing                         |745 (1.9%)         |\n|**Log Hours with Children**     |                   |\n|Mean (SD)                       |1.18 (1.61)        |\n|Median [Min, Max]               |0.0341 [0, 5.13]   |\n|Missing                         |1242 (3.1%)        |\n|**Log Hours Commuting**         |                   |\n|Mean (SD)                       |1.50 (0.832)       |\n|Median [Min, Max]               |1.61 [0, 4.40]     |\n|Missing                         |1242 (3.1%)        |\n|**Log Hours Exercising**        |                   |\n|Mean (SD)                       |1.55 (0.846)       |\n|Median [Min, Max]               |1.61 [0, 4.40]     |\n|Missing                         |1242 (3.1%)        |\n|**Log Hours on Housework**      |                   |\n|Mean (SD)                       |2.14 (0.782)       |\n|Median [Min, Max]               |2.20 [0, 5.13]     |\n|Missing                         |1242 (3.1%)        |\n|**Log Household Income**        |                   |\n|Mean (SD)                       |11.4 (0.765)       |\n|Median [Min, Max]               |11.5 [0.685, 14.9] |\n|Missing                         |3067 (7.7%)        |\n|**Male**                        |                   |\n|0                               |24766 (62.5%)      |\n|1                               |14767 (37.3%)      |\n|Missing                         |102 (0.3%)         |\n|**Neuroticism**                 |                   |\n|Mean (SD)                       |3.49 (1.15)        |\n|Median [Min, Max]               |3.48 [1.00, 7.00]  |\n|Missing                         |10 (0.0%)          |\n|**Non-heterosexual**            |                   |\n|0                               |35100 (88.6%)      |\n|1                               |2562 (6.5%)        |\n|Missing                         |1973 (5.0%)        |\n|**NZ Deprivation Index**        |                   |\n|Mean (SD)                       |4.77 (2.73)        |\n|Median [Min, Max]               |4.05 [1.00, 10.0]  |\n|Missing                         |255 (0.6%)         |\n|**Occupational Prestige Index** |                   |\n|Mean (SD)                       |54.1 (16.5)        |\n|Median [Min, Max]               |54.0 [10.0, 90.0]  |\n|Missing                         |536 (1.4%)         |\n|**Openness**                    |                   |\n|Mean (SD)                       |4.96 (1.12)        |\n|Median [Min, Max]               |5.00 [1.00, 7.00]  |\n|Missing                         |3 (0.0%)           |\n|**Parent**                      |                   |\n|0                               |11539 (29.1%)      |\n|1                               |27776 (70.1%)      |\n|Missing                         |320 (0.8%)         |\n|**Has Partner**                 |                   |\n|Mean (SD)                       |0.752 (0.432)      |\n|Median [Min, Max]               |1.00 [0, 1.00]     |\n|Missing                         |1244 (3.1%)        |\n|**Political Conservatism**      |                   |\n|Mean (SD)                       |3.59 (1.38)        |\n|Median [Min, Max]               |3.97 [1.00, 7.00]  |\n|Missing                         |2682 (6.8%)        |\n|**Religious Identification**    |                   |\n|Mean (SD)                       |2.36 (2.18)        |\n|Median [Min, Max]               |1.00 [1.00, 7.00]  |\n|Missing                         |1050 (2.6%)        |\n|**Rural Classification**        |                   |\n|High Urban Accessibility        |24406 (61.6%)      |\n|Medium Urban Accessibility      |7431 (18.7%)       |\n|Low Urban Accessibility         |4818 (12.2%)       |\n|Remote                          |2241 (5.7%)        |\n|Very Remote                     |486 (1.2%)         |\n|Missing                         |253 (0.6%)         |\n|**Sample Frame Opt-In**         |                   |\n|0                               |38485 (97.1%)      |\n|1                               |1150 (2.9%)        |\n|**Short Form Health**           |                   |\n|Mean (SD)                       |5.05 (1.17)        |\n|Median [Min, Max]               |5.04 [1.00, 7.00]  |\n|Missing                         |6 (0.0%)           |\n|**Smoker**                      |                   |\n|0                               |35771 (90.3%)      |\n|1                               |2880 (7.3%)        |\n|Missing                         |984 (2.5%)         |\nDemographic statistics for New Zealand Attitudes and Values Cohort: {baseline_wave_glued}.\n:::\n\n\n### Sample Statistics: Exposure Variable {#appendix-exposure} \n\n<!-- @tbl-sample-exposures presents sample statistics for the exposure variable, religious service attendance, during the baseline and exposure waves. This variable was not measured in part of NZAVS time 12 (years 2020-2021) and part of NZAVS time 13 (years 2021-2022). To address missingness, if a value was observed after NZAVS time 14, we carried the previous observation forward and created and NA indicator. If there was no future observation, the participant was treated as censored, and inverse probability of censoring weights were applied, following our standard method for handling missing observations (see mansucript **Method**/**Handling of Missing Data**). Here, our carry-forward imputation approach may result in conservative causal effect estimation because it introduces measurement error. However, this approach would not generally bias causal effect estimation away from the null because the measurement error is unsystematic and random and unrelated to the outcomes. -->\n\n\n::: {#tbl-appendix-exposures}\n\n|                          |2018              |2019              |\n|:-------------------------|:-----------------|:-----------------|\n|                          |(N=39635)         |(N=39635)         |\n|**Extraversion**          |                  |                  |\n|Mean (SD)                 |3.91 (1.20)       |3.86 (1.19)       |\n|Median [Min, Max]         |3.96 [1.00, 7.00] |3.79 [1.00, 7.00] |\n|Missing                   |0 (0%)            |11117 (28.0%)     |\n|**Extraversion (binary)** |                  |                  |\n|[1.0,4.0]                 |21138 (53.3%)     |15637 (39.5%)     |\n|(4.0,7.0]                 |18497 (46.7%)     |12881 (32.5%)     |\n|Missing                   |0 (0%)            |11117 (28.0%)     |\nDemographic statistics for New Zealand Attitudes and Values Cohort waves 2018.\n:::\n\n{{< pagebreak >}}\n\n### Sample Statistics: Outcome Variables {#appendix-outcomes} \n\n::: {#tbl-appendix-outcomes}\n\n|                            |2018              |2020              |Overall           |\n|:---------------------------|:-----------------|:-----------------|:-----------------|\n|                            |(N=39635)         |(N=39635)         |(N=79270)         |\n|**Social Belonging**        |                  |                  |                  |\n|Mean (SD)                   |5.14 (1.07)       |5.06 (1.09)       |5.11 (1.08)       |\n|Median [Min, Max]           |5.31 [1.00, 7.00] |5.05 [1.00, 7.00] |5.30 [1.00, 7.00] |\n|Missing                     |7 (0.0%)          |13278 (33.5%)     |13285 (16.8%)     |\n|**Anxiety**                 |                  |                  |                  |\n|Mean (SD)                   |1.21 (0.774)      |1.17 (0.756)      |1.19 (0.767)      |\n|Median [Min, Max]           |1.00 [0, 4.00]    |1.00 [0, 4.00]    |1.00 [0, 4.00]    |\n|Missing                     |51 (0.1%)         |13275 (33.5%)     |13326 (16.8%)     |\n|**Depression**              |                  |                  |                  |\n|Mean (SD)                   |0.584 (0.751)     |0.550 (0.723)     |0.571 (0.740)     |\n|Median [Min, Max]           |0.333 [0, 4.00]   |0.333 [0, 4.00]   |0.333 [0, 4.00]   |\n|Missing                     |54 (0.1%)         |13273 (33.5%)     |13327 (16.8%)     |\n|**Life Satisfaction**       |                  |                  |                  |\n|Mean (SD)                   |5.30 (1.20)       |5.25 (1.23)       |5.28 (1.21)       |\n|Median [Min, Max]           |5.50 [1.00, 7.00] |5.50 [1.00, 7.00] |5.50 [1.00, 7.00] |\n|Missing                     |260 (0.7%)        |13560 (34.2%)     |13820 (17.4%)     |\n|**Hours of Exercise (log)** |                  |                  |                  |\n|Mean (SD)                   |1.55 (0.846)      |1.63 (0.839)      |1.58 (0.844)      |\n|Median [Min, Max]           |1.61 [0, 4.40]    |1.78 [0, 4.40]    |1.61 [0, 4.40]    |\n|Missing                     |1242 (3.1%)       |13770 (34.7%)     |15012 (18.9%)     |\n|Meaning: Purpose            |                  |                  |                  |\n|Mean (SD)                   |5.20 (1.41)       |5.15 (1.44)       |5.18 (1.42)       |\n|Median [Min, Max]           |5.05 [1.00, 7.00] |5.04 [1.00, 7.00] |5.04 [1.00, 7.00] |\n|Missing                     |1010 (2.5%)       |13650 (34.4%)     |14660 (18.5%)     |\n|Meaning: Sense              |                  |                  |                  |\n|Mean (SD)                   |5.71 (1.22)       |5.71 (1.19)       |5.71 (1.20)       |\n|Median [Min, Max]           |5.99 [1.00, 7.00] |5.99 [1.00, 7.00] |5.99 [1.00, 7.00] |\n|Missing                     |128 (0.3%)        |13162 (33.2%)     |13290 (16.8%)     |\n|**Neighbourhood Community** |                  |                  |                  |\n|Mean (SD)                   |4.19 (1.66)       |4.38 (1.57)       |4.27 (1.63)       |\n|Median [Min, Max]           |4.03 [1.00, 7.00] |4.95 [1.00, 7.00] |4.04 [1.00, 7.00] |\n|Missing                     |212 (0.5%)        |13202 (33.3%)     |13414 (16.9%)     |\n|**Pwi**                     |                  |                  |                  |\n|Mean (SD)                   |7.09 (1.66)       |7.18 (1.63)       |7.12 (1.65)       |\n|Median [Min, Max]           |7.29 [0, 10.0]    |7.47 [0, 10.0]    |7.46 [0, 10.0]    |\n|Missing                     |41 (0.1%)         |13120 (33.1%)     |13161 (16.6%)     |\n|**Rumination**              |                  |                  |                  |\n|Mean (SD)                   |0.853 (1.00)      |0.797 (0.959)     |0.831 (0.987)     |\n|Median [Min, Max]           |0.955 [0, 4.00]   |0.0495 [0, 4.00]  |0.953 [0, 4.00]   |\n|Missing                     |135 (0.3%)        |13335 (33.6%)     |13470 (17.0%)     |\n|**Self Esteem**             |                  |                  |                  |\n|Mean (SD)                   |5.14 (1.28)       |5.13 (1.27)       |5.14 (1.28)       |\n|Median [Min, Max]           |5.34 [1.00, 7.00] |5.34 [1.00, 7.00] |5.34 [1.00, 7.00] |\n|Missing                     |11 (0.0%)         |13280 (33.5%)     |13291 (16.8%)     |\n|**Social Support**          |                  |                  |                  |\n|Mean (SD)                   |5.95 (1.12)       |5.94 (1.12)       |5.95 (1.12)       |\n|Median [Min, Max]           |6.30 [1.00, 7.00] |6.29 [1.00, 7.00] |6.30 [1.00, 7.00] |\n|Missing                     |30 (0.1%)         |13112 (33.1%)     |13142 (16.6%)     |\nOutcome variables measured at {baseline_wave_glued} and {outcome_wave}\n:::\n\n\n{{< pagebreak >}}\n\n## Appendix C: Transition Matrix to Check The Positivity Assumption {#appendix-transition}\n\n\n\n::: {#tbl-transition .cell tbl-cap='Transition Matrix Showing Change'}\n\n|From / To | State 0| State 1| Total|\n|:---------|-------:|-------:|-----:|\n|State 0   |   17572|    2271| 19843|\n|State 1   |    2400|    6275|  8675|\n:::\n\n\nThese transition matrices capture shifts in states between consecutive waves. Each cell shows the count of individuals transitioning from one state to another. Rows are the initial state (From), columns the subsequent state (To). **Diagonal entries** (in **bold**) mark those who stayed in the same state.\n\n\n{{< pagebreak >}}\n\n## Appendix D: Approach to Heterogeneity {#appendix-cate-validation}\n\n\n## Appendix X. Estimating and Interpreting Heterogeneous Treatment Effects with **grf**\n\nHere we explain a heterogeneous‐treatment‐effect (HTE) analysis using causal forests [@grf2024]. In our workflow, we move from the average treatment effect (ATE) to individualised effects, quantify the practical value of targeting, and finish with interpretable decision rules.\n\n\n### 1 Average Treatment Effect (ATE)\n\nThe ATE answers: *'What would happen, on average, if everyone received treatment versus no one?'*\n\n$$\n    \\text{ATE}=E[Y(1)-Y(0)].\n$$\n\nUsing the `grf` package, we estimate the ATE doubly-robustly.  Because we analyse several outcomes, we adjust ATE *p*-values with bonferroni ($\\alpha$ = 0.05) to control the family-wise error rate.\n\n\n\n\n### 2 Do Effects Vary?  Formal Test of Heterogeneity\n\nDefine the conditional average treatment effect (CATE)\n\n$$\n  \\tau(x)=E[Y(1)-Y(0)\\mid X=x].\n$$\n\nIf $\\tau(x)$ is constant, effects are homogeneous; otherwise they vary. Classical interaction models impose strong forms; **grf** uses *causal forests* to discover complex, nonlinear heterogeneity [@wager2018].  We assess heterogeneity with RATE *p*-values corrected via Benjamini–Hochberg false-discovery-rate adjustment (q = 0.1), controlling the false-discovery rate [@benjamini1995controlling].\n\n\n\n\n### 3 Causal Forests for Individualised Estimates\n\nA causal forest is an ensemble of 'honest' causal trees that split on covariates to maximise treated–control contrasts. For each unit $i$ we obtain\n\n$$\n  \\widehat{\\tau}(x_i)\n$$\n\nStrengths are flexibility, orthogonalisation, and per-person estimates.\n\n\n### 4 Built-in Protection Against Over-fitting\n\n  Honesty (split half/estimate half) plus out-of-bag (OOB) predictions yield unbiased $\\widehat{\\tau}(x)$ and standard errors without manual hyper-tuning.\n\n\n### 5 Missing Data Handling\n\n**grf** deploys 'Missing Incorporated in Attributes' (MIA): missingness is a valid split, so cases stay in the analysis -- no ad-hoc imputation required.\n\n\n### 6 Testing for **Actionable** Heterogeneity: the TOC & RATE Metrics\n\nRanking units by $\\widehat{\\tau}$ defines a **Targeting Operator Characteristic** (TOC) curve: the cumulative gain from treating the top fraction $q$ of predicted responders. Two scalar summaries:\n\n- **RATE AUTOC** – area under the entire TOC; emphasises the very highest responders.\n- **RATE Qini** – weighted area with weight $q$; rewards sustained gains across larger coverage [@yadlowsky2021evaluating].\n\nUnder $H_0{:}\\tau(x)$ constant, both equal 0.\n`grf::rank_average_treatment_effect()` supplies point estimates, standard errors, and $t$-tests.\n\n**Multiplicity control**: We adjust AUTOC and Qini *p*-values with Benjamini–Hochberg false-discovery-rate adjustment (q = 0.1) before declaring actionable heterogeneity.\n\nHere is an **interpretation tip**:\n\n* AUTOC answers *'How sharply can we prioritise?'*\n* Qini answers *'How valuable is targeting when budgets are modest but not tiny?'*\n\n### 7 Visualising Policy Value: the Qini Curve\n\nPlotting the Qini curve (cumulative gain vs $q$) reveals where returns plateau. Investigators (and policy audiences) can see at a glance whether benefits concentrate in, say, the top 20 % or persist up to 50 %.\n\n\n### 8 Valid Inference for RATE / Qini\n\nAlthough OOB predictions are out-of-sample per tree, they inherit forest-level dependence. We use an explicit **sample split**:\n\n1. **Train set**: fit the causal forest and compute $\\widehat{\\tau}(x)$.\n2. **Test set**: compute RATE AUTOC/Qini and run $H_0$ tests.\n\nThis second split yields honest policy evaluation and guards against optimistic bias [@grf2024].\n\n### 9 From Black Box to Simple Rules: Policy Trees\n\nStakeholders value transparent criteria. The **policytree** algorithm takes $\\widehat{\\tau}(x)$ or doubly-robust scores and learns a shallow decision tree that maximises expected welfare [@policytree_package_2024].\n\n*Advantages*: interpretability, the possibility of fairness constraints, and easy communication (e.g., *'treat if age < 25 and baseline severity high'*).\n\nTraining mirrors the split above: learn the tree on one fold, evaluate welfare on another.\n\n> **Caveat**  Splits identify predictors of *effect variation*, not causal levers. Changing a covariate in the tree does **not** guarantee an effect on $\\tau(x)$.\n\n\n### 10 Ethical and Practical Considerations\n\nStatistical optimisation rarely aligns perfectly with equity or political feasibility. Decisions about who *should* receive treatment belong to democratic processes that weigh fairness, cost, and broader social values.\n\n\n### Summary Checklist\n\n  | Stage | Tool | Key Output | Guard-rail |\n  |-------|------|------------|------------|\n  | 1 ATE | `average_treatment_effect` | $\\widehat{\\text{ATE}}$ | Doubly-robust |\n  | 2 – 3 CATE | `causal_forest` | $\\widehat{\\tau}(x)$ | Honest trees |\n  | 6 Heterogeneity test | `rank_average_treatment_effect` | AUTOC, Qini + $p$ | Sample split |\n  | 7 Visualise | Qini curve | Gain vs $q$ | Same test fold |\n  | 9 Policy tree | `policy_tree` | Decision rule | Cross-validation + test fold |\n\n  : This workflow delivers both rigorous inference and clear guidance for applied researchers: *How large is heterogeneity? When does targeting pay off? And can we express a good policy in a few, defensible rules?*\n\n{{< pagebreak >}}\n\n## References {.appendix-refs}\n\n\n\n\n\n",
    "supporting": [
      "initial_quarto_document_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}